default_context:
  project_name: 'prorang'
  project_slug: 'prorang'
  domain_main: 'dovinside.kro.kr'
  domain_staging: 'stag.dovinside.kro.kr'
  docker_swarm_stack_name_main: 'dovinside-kro-kr'
  docker_swarm_stack_name_staging: 'stag-dovinside-kro-kr'
  secret_key: 'qpwoei1!'
  first_superuser: 'admin@dovinside.kro.kr'
  first_superuser_password: 'qpwoei1!'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.dovinside.kro.kr", "https://stag.dovinside.kro.kr", "https://dovinside.kro.kr", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '8000'
  smtp_host: ''
  smtp_user: 'dove'
  smtp_password: 'qpwoei1!'
  smtp_emails_from_email: 'info@dovinside.kro.kr'
  postgres_password: 'qpwoei1!'
  pgadmin_default_user: 'admin@dovinside.kro.kr'
  pgadmin_default_user_password: 'qpwoei1!'
  traefik_constraint_tag: 'dovinside.kro.kr'
  traefik_constraint_tag_staging: 'stag.dovinside.kro.kr'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:qpwoei1!'
  sentry_dsn: ''
  docker_image_prefix: '/'
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
